### ISSUE TITLE
fix the assetlib download

### ISSUE THREAD

**Issue by leleleSDX** [Ev01/PlatformerController2D#1]
![platform2dgodot](https://user-images.githubusercontent.com/6260996/235925836-257b25c1-b1c6-4be1-9ceb-cc2dff3e1dfd.JPG)

there's too many things to uncheck. godot doesn't have the uncheck all option. i don't need to download your caches. it's easier to just manually download the required files from github.

**Comment by Ev01** [comment]
This should be fixed now but won't update immediately on the asset store because the changes need to be approved first.
